eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-core
  redis:
    host: localhost
    port: 6379

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 12000
        readTimeout: 12000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000







