eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-zuul
  redis:
    host: localhost
    port: 6379

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000

zuul:
  routes:
    api-a:
      path: /core/**
      serviceId: service-core
      sensitiveHeaders: "*"
    api-b:
      path: /user/**
      serviceId: service-user
      sensitiveHeaders: "*"

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 12000
