eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-user
  redis:
    host: localhost
    port: 6379
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 24000

mail:
  from:
    account: register@yaochow.com
    password: Abcd1234
  host: smtp.yaochow.com

user.md5.password.key: www.yaochow.com
user.md5.uid.key: www.yaochow.com
user.email.content: "请点击下方连接确认注册，若非本人操作请忽略此邮件。\r\n http://www.yaochow.com/user/confirm?username=%s&email=%s&key=%s"
user.register.confirm.result: "<script>alert('Successful');window.location.href='http://www.yaochow.com';</script>"




